import type { Metadata } from "next";

import { Roboto, Inter } from "next/font/google";

const anton = Roboto({
  subsets: ["latin"],
  weight: ["400", "300", "100", "700"],
});

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={anton.className}>{children}</body>
    </html>
  );
}
